#!/usr/bin/env bash
set -euo pipefail

ROOT="$(pwd)"
LOG="$ROOT/da_fix_sharedarraybuffer_v2.log"
exec > >(tee -a "$LOG") 2>&1

echo "=== [DA] SharedArrayBuffer fix v2 - $(date) ==="
echo "ROOT=$ROOT"

if ! command -v node >/dev/null 2>&1; then
  echo "❌ node introuvable"
  exit 1
fi

APPS=("apps/client" "apps/courier" "apps/merchant")
WRAPPER="entry.sharedarraybuffer.js"

for APP in "${APPS[@]}"; do
  APP_DIR="$ROOT/$APP"
  PKG="$APP_DIR/package.json"

  echo ""
  echo ">>> $APP"

  if [ ! -f "$PKG" ]; then
    echo "⚠️ package.json introuvable: $PKG"
    continue
  fi

  # 1) Polyfill (écrasé volontairement pour être sûr du contenu)
  cat > "$APP_DIR/polyfills.js" <<'POLY'
// polyfills.js
if (typeof globalThis.SharedArrayBuffer === 'undefined') {
  globalThis.SharedArrayBuffer = globalThis.ArrayBuffer;
}
POLY
  echo "✅ polyfills.js OK -> $APP_DIR/polyfills.js"

  # 2) Lire main actuel
  MAIN="$(node -e "const p=require('${PKG}'); process.stdout.write(String(p.main||''));")"
  if [ -z "$MAIN" ]; then
    MAIN="expo-router/entry"
    echo "ℹ️ main absent -> fallback: $MAIN"
  else
    echo "ℹ️ main actuel: $MAIN"
  fi

  # Si déjà patché
  if [ "$MAIN" = "$WRAPPER" ]; then
    echo "ℹ️ Déjà patché (main=$WRAPPER)"
    continue
  fi

  # 3) Déterminer la cible à require() (module vs fichier local)
  REQ="$MAIN"
  if [[ "$REQ" == .* || "$REQ" == /* ]]; then
    : # chemin explicite -> OK
  else
    # Si c'est un fichier local (ex: index.js / src/index.ts), on force "./"
    if [ -f "$APP_DIR/$REQ" ] || [ -f "$APP_DIR/$REQ.js" ] || [ -f "$APP_DIR/$REQ.ts" ] || [ -f "$APP_DIR/$REQ.tsx" ] || [ -f "$APP_DIR/$REQ.jsx" ]; then
      REQ="./$REQ"
    fi
  fi

  TS="$(date +%Y%m%d_%H%M%S)"
  cp "$PKG" "$PKG.bak.$TS"
  echo "🧷 Backup: $PKG.bak.$TS"

  # 4) Créer le wrapper
  cat > "$APP_DIR/$WRAPPER" <<EOF2
// $WRAPPER
// Generated by da_fix_sharedarraybuffer_v2.sh
// Previous main: $MAIN
require("./polyfills");
require("$REQ");
EOF2
  echo "✅ Wrapper créé: $APP_DIR/$WRAPPER (require -> $REQ)"

  # 5) Patch package.json -> main = wrapper (et garde trace de l'ancien main)
  node - <<NODE
const fs = require("fs");
const pkgPath = "${PKG}";
const pkg = JSON.parse(fs.readFileSync(pkgPath,"utf8"));

if (!("delishAfricaOriginalMain" in pkg)) pkg.delishAfricaOriginalMain = pkg.main || null;
pkg.main = "${WRAPPER}";

fs.writeFileSync(pkgPath, JSON.stringify(pkg,null,2) + "\\n","utf8");
console.log("✅ package.json main =", pkg.main);
NODE

done

echo ""
echo "=== OK ==="
echo "📌 Ensuite:"
echo "1) Stop Metro si il tourne"
echo "2) Relance avec cache clear (selon vos scripts):"
echo "   - pnpm client:dev -- --clear"
echo "   - ou: pnpm -C apps/client expo start --dev-client -c"
echo "3) iPhone: force-quit l’app Client puis relance"
echo "📄 Log: $LOG"
