#!/usr/bin/env bash
set -euo pipefail

### =========================
###  DelishAfrica ULTRA RESET
###  - tue tmux + bundlers + quick tunnels
###  - force API URL identique pour 3 apps
###  - relance API + 3 Metro (ports fixes)
### =========================

SESSION="delish"
ROOT="/opt/delishafrica/monorepo"

API_DIR="$ROOT/services/api"
CLIENT_DIR="$ROOT/apps/client"
COURIER_DIR="$ROOT/apps/courier"
MERCHANT_DIR="$ROOT/apps/merchant"

API_PORT="3010"          # votre cible annoncée
METRO_CLIENT="8082"
METRO_COURIER="8081"
METRO_MERCHANT="8083"

API_HTTPS="https://api.delishafrica.me"   # source de vérité côté apps
# (si vous changez de domaine, changez UNIQUEMENT ici)

say(){ echo -e "\n\033[1;36m==> $*\033[0m"; }
ok(){  echo -e "\033[1;32m✔\033[0m $*"; }
warn(){ echo -e "\033[1;33m⚠\033[0m $*"; }
die(){ echo -e "\033[1;31m✖\033[0m $*"; exit 1; }

need_dir(){ [ -d "$1" ] || die "Dossier introuvable: $1"; }

pick_cmd() {
  local dir="$1"
  local pj="$dir/package.json"
  if [ -f "$pj" ]; then
    if grep -q '"start:dev"' "$pj"; then echo "pnpm start:dev"; return; fi
    if grep -q '"dev"' "$pj"; then echo "pnpm dev"; return; fi
    if grep -q '"start"' "$pj"; then echo "pnpm start"; return; fi
  fi
  echo "pnpm start"
}

expo_cmd() {
  local port="$1"
  # --tunnel : iOS friendly ; -c : clear bundler cache ; --dev-client : vos Dev Clients
  echo "EXPO_PUBLIC_API_URL='$API_HTTPS' API_URL='$API_HTTPS' API_BASE_URL='$API_HTTPS' pnpm exec expo start --dev-client --tunnel -c --port $port"
}

write_env() {
  local dir="$1"
  # On écrit un .env simple et on laisse le reste au code.
  cat > "$dir/.env" <<EOF
# AUTO-GENERATED by da_ultra_reset.sh
EXPO_PUBLIC_API_URL=https://api.delishafrica.me
API_URL=$API_HTTPS
API_BASE_URL=https://api.delishafrica.me
EOF
}

say "0) Sanity check paths"
need_dir "$ROOT"
need_dir "$API_DIR"
need_dir "$CLIENT_DIR"
need_dir "$COURIER_DIR"
need_dir "$MERCHANT_DIR"
ok "Paths OK ($ROOT)"

say "1) STOP: tmux + processes + ports"
tmux kill-server 2>/dev/null || true

# Stop quick tunnels cloudflared (trycloudflare) s'il y en a
pkill -f "cloudflared.*trycloudflare" 2>/dev/null || true
pkill -f "cloudflared tunnel" 2>/dev/null || true

# Stop expo/metro (ciblé)
pkill -f "expo start" 2>/dev/null || true
pkill -f "MetroBundler" 2>/dev/null || true
pkill -f "react-native" 2>/dev/null || true

# Libère ports (API + Metro + classiques)
for p in "$API_PORT" 4001 4010 8080 8081 8082 8083 8084 19000 19001 19002 19006; do
  fuser -k "${p}/tcp" 2>/dev/null || true
done
ok "tmux/process/ports nettoyés"

say "2) Clear caches (safe)"
rm -rf /tmp/metro-* /tmp/haste-map-* /tmp/react-* 2>/dev/null || true
rm -rf ~/.expo ~/.cache/expo ~/.npm/_cacache 2>/dev/null || true
ok "Caches OK"

say "3) Force ONE API URL in all apps (.env + runtime env)"
write_env "$CLIENT_DIR"
write_env "$COURIER_DIR"
write_env "$MERCHANT_DIR"
ok "Env forcé: $API_HTTPS"

say "4) Start tmux session with 4 windows (api / courier / client / merchant)"
tmux new-session -d -s "$SESSION" -n api
tmux set-option -t "$SESSION" mouse on >/dev/null

API_CMD="$(pick_cmd "$API_DIR")"

# API (IMPORTANT: on force PORT=3010 au runtime)
tmux send-keys -t "$SESSION:api" "cd '$API_DIR' && PORT='$API_PORT' $API_CMD" C-m

# Courier (8081)
tmux new-window -t "$SESSION" -n courier
tmux send-keys -t "$SESSION:courier" "cd '$COURIER_DIR' && rm -rf .expo .expo-shared >/dev/null 2>&1 || true; $(expo_cmd "$METRO_COURIER")" C-m

# Client (8082)
tmux new-window -t "$SESSION" -n client
tmux send-keys -t "$SESSION:client" "cd '$CLIENT_DIR' && rm -rf .expo .expo-shared >/dev/null 2>&1 || true; $(expo_cmd "$METRO_CLIENT")" C-m

# Merchant (8083)
tmux new-window -t "$SESSION" -n merchant
tmux send-keys -t "$SESSION:merchant" "cd '$MERCHANT_DIR' && rm -rf .expo .expo-shared >/dev/null 2>&1 || true; $(expo_cmd "$METRO_MERCHANT")" C-m

say "5) Health checks (local first, then domain)"
sleep 3

echo
echo "---- LISTENING (API_PORT=$API_PORT) ----"
ss -lntp | egrep ":($API_PORT|4001)\b" || true

echo
echo "---- LOCAL TESTS ----"
echo "# 3010 /api/health"
curl -sS --max-time 3 "http://127.0.0.1:${API_PORT}/api/health" || true
echo
echo "# 3010 /api/v1/health"
curl -sS --max-time 3 "http://127.0.0.1:${API_PORT}/api/v1/health" || true
echo
echo "# 4001 /api/health (au cas où votre API est encore Dockerisée sur 4001)"
curl -sS --max-time 3 "http://127.0.0.1:3010/api/health" || true
echo

echo
echo "---- DOMAIN TEST ----"
curl -sS -I --max-time 6 "${API_HTTPS}/api/health" || true
echo

ok "DONE. Attach: tmux attach -t $SESSION"
echo "If apps still show old API inside UI -> hard kill iPhone apps (swipe up) + Reload in Dev Menu."
